services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d test -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      DATABASE_URI: "postgresql+psycopg://postgres:password@127.0.0.1:5432/test"
    ports:
      - "80:80"
    depends_on:
      pg:
        condition: service_healthy

volumes:
  db-data: